apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-metrics
  namespace: monitoring
  labels:
    release: monitoring   # must match your Prometheus Helm release name
spec:
  selector:
    matchLabels:
      app: flask-metrics
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
