apiVersion: v1
kind: Service
metadata:
  name: flask-metrics
  labels:
    app: flask-metrics
spec:
  selector:
    app: flask-metrics
  ports:
    - name: http
      port: 5000
      targetPort: http
