apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-metrics
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: flask-metrics
  namespaceSelector:
    matchNames: ["default"]
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
